version: '3'
services:
  moxy_mysql:
    image: mysql:5.7.21
    container_name: moxy_mysql_db
    volumes:
      - ./data:/var/lib/mysql
    # ports:
    #   - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=test123
    networks:
      - webgateway
networks:
  webgateway:
    external:
      name: moxy_gateway
